# Generated by Django 4.1.4 on 2023-01-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natureapp', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='img',
            new_name='image',
        ),
    ]
