# Generated by Django 4.1.4 on 2023-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natureapp', '0003_rename_name_purchase_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='image',
            field=models.ImageField(upload_to='picks'),
        ),
    ]
